### ISSUE TITLE
Ability to Reorder Appenders/Loggers in MainWindow

### ISSUE THREAD

**Issue by alexleen** [alexleen/log4net-config-editor#4]
It might be nice to be able to adjust the order of the children in the main window. This would allow the user to reorder the children of the 'log4net' XML element in the actual file, if desired.

**Comment by atown-24** [comment]
Note that we'll have to turn off the sorting support on the data grid since the user can sort each column (I assume this only changes the view and not the underlying collection).

**Comment by alexleen** [comment]
The whole point of this tool is to hide the XML configuration file. Ordering the XML elements should be unnecessary. Closing as "wontfix" for now.
