### ISSUE TITLE
Code split/architecture

### ISSUE THREAD

**Issue by Ledragon** [alexleen/log4net-config-editor#67]
Hello,
Thanks for the project. I am currently in the mental process of being able to do the same kind of things via a web interface a Web API. Since it seems that a lot of the heavy lifting of reading/writing the xml file is done in this project, I think I could reuse that. However, all that logic currently resides in the same project as the UI, which in my case would be a burden, as I don't need all the WPF layer for my API.

Do you already have a view on how you would split your project to make it more widely usable? Or maybe you did not think about that at all? Would you mind that I try something and upload it in my fork of the project for your review?
 Or am I just a jerk who criticizes your amazing work, and might as well go to hell? :smiling_imp:

**Comment by alexleen** [comment]
Haha, no way go for it!

I've been thinking about this for #2. I started to move all XML manipulation to Editor\XML, but there's still quite a lot of references to System.XML in other parts of the app (indicating that there is more XML manipulation going on outside of Editor\XML).

Maybe we should consider making another project that results in a NuGet package focusing exclusively on the manipulation of log4net XML.

**Comment by Ledragon** [comment]
Good to know, it's always hard to convey an appropriate tone via text message :-)

I actually already started on Friday afternoon, creating a couple libraries and starting to move code around. I'll try comitting it on my fork, so that we have a basis to start discussing on. My major concern at the moment is that models and view models do not seem to be separated in your implementation (i.e. directly implement INotifyPropertyChanged), making it difficult to extract these. XML manipulation seems more or less split (though leaking here and there, but could be easily fixable).

Making it a nuget package would be absolutely awesome of course!

I have a couple of extra thoughts on that regard though:
* should we think about a nomenclature scheme? Editor is pretty general I think
* should the library(ies) be made .NET Standard compliant? They could be used in conjunction with .NET Core, which I think would be cool (but I have no experience in that regard)

**Comment by Ledragon** [comment]
I pushed my changes [here](https://github.com/Ledragon/log4net-config-editor) if you want to have a look at my preliminary work. I could be available this Sunday afternoon (like 15:00 Eastern European Time) if you wan to discuss on gitter on how to move forward

**Comment by alexleen** [comment]
Sounds good. Room: https://gitter.im/log4net-config-editor/XML-Manipulation-Encapsulation
