### ISSUE TITLE
Easy Disable Appender From MainWindow

### ISSUE THREAD

**Issue by alexleen** [alexleen/log4net-config-editor#7]
It would be nice if you could easily disable any appender from the MainWindow. It's often the case that you'll have many appenders that are useful for specific debugging situations that should be "kept around" but not necessarily "on". We could do this via a "Remove Refs" button on each child row.

**Comment by atown-24** [comment]
As for an async forwarder, it might be nice to list appenders referenced _in_ an async forwarder much like in the root logger. This would improve management of these appenders, at least.

**Comment by alexleen** [comment]
Maybe appenders and loggers (or anyone capable of containing references) should list both _outgoing_ and _incoming_ references. Outgoing being references contained in the _current_ element and incoming being references to _this_ element from other elements.
